---
downloads: ~/.ansible-downloads/

#configure_dotfiles: false

configure_dock: true
dockitems_remove:
 - Launchpad
 - Mail
 - Maps
 - Photos
 - Facetime
 - Contacts
 - TV
 - Podcasts
 - Music
 - News
 - 'App Store'

dockitems_persist: 
  - name: "WhatsApp"
    path: "/Applications/WhatsApp.app/"
    pos: 4
  - name: "Hyper"
    path: "/Applications/Hyper.app/"
    pos: 5
  - name: "Discord"
    path: "/Applications/Discord.app/"
    pos: 6
  - name: "1password"
    path: "/Applications/1password.app/"
    pos: 7
    - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 8
  - name: "Docker" 
    path: "/Applications/Docker.app/"
    pos: 9

# dotfiles_repo: https://github.com/jediBui/dotfiles.git
# dotfiles_repo_local_destination: ~/Repo/dotfiles
# dotfiles_files:
#   - .hyper.js
#   - .osx
#   - .vimrc
#   - .zshrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - git
  - iperf
  - nmap
  - openssl
  - pygments
  - spaceship # ohmyzsh theme
  - ssh-copy-id
  - wget
  - wrk-trello

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - epk/epk

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - alfred
  - authy
  - discord
  - docker
  - fig
  - font-sf-mono-nerd-font
  - google-chrome
  - hyper
  - iina
  - royal-tsx
  - slack
#  - thinkorswim
  - visual-studio-code
  - WhatsApp

